apiVersion: v1
kind: Service
metadata:
  name: ocpi-simulator
  labels:
    app: ocpi-simulator
spec:
  type: ClusterIP
  selector:
    app: ocpi-simulator
  ports:
    - name: http
      port: 8081
      targetPort: http
